Description: 'Amazon EKS Service Role'
Parameters:
  EKSRoleName:
    Description: EKS Cluster Role Name
    Type: String
  NodeRoleName:
    Description: EKS Cluster Node Role Name
    Type: String
Resources:
  eksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      RoleName:
        !Sub EKSRoleName

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      RoleName:
        !Sub NodeRoleName
Outputs:
  ClusterRoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt eksServiceRole.Arn
    Export:
      Name: "Cluster-RoleArn"

  NodeRoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes Nodes
    Value: !GetAtt NodeInstanceRole.Arn
    Export:
      Name: "Node-RoleArn"
  NodeRoleName:
    Description: The role Name that Amazon EKS will use to create AWS resources for Kubernetes Nodes
    Value:
      !Sub NodeRoleName
    Export:
      Name: "Node-RoleName"